services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    hostname: api
    env_file: .env
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - bridge
    depends_on:
      - db
      # - firebase
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate dev && npm run start:debug"
    restart: on-failure

  db:
    image: postgres:alpine
    container_name: db
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: posts-api
    ports:
      - 5432:5432
    networks:
      - bridge
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  bridge:

volumes:
  pgdata:
